# Generated by Django 3.2.7 on 2023-05-16 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('letra', models.TextField(max_length=1220)),
            ],
            options={
                'verbose_name': 'Letras',
                'verbose_name_plural': 'Letras',
                'ordering': ['id'],
            },
        ),
    ]
